apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:kIrzVa3OnHmEtsGpRU/PRwl4efywxr50mkPqNmM52PeYMCQr8S+Vkw==,iv:AJ7ZAjtEWLkQGTPuhdPGC6GzgNXLMPiXUsfSRsXQzWU=,tag:ornsiitqyiS9v6R84qLGOg==,type:str]
sops:
  age:
    - recipient: age130g6zdklea9zw6n4ddm7ffn4dewvyexjps0q9zfse2df72umqazslr0lc3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RFp5QjYwVUM2SXEvN3hz
        dytocGNGQmJRVk1STUZ4OVhaRTNkN21LYVhzClB2T1ZxdWpQT1dOekdXVDVxeUZR
        eHMrSkJkTng4aXZ3dW9vS3h6ZU1OdlUKLS0tIDNrbEV3ZkRMbVAxYXVhYTRmTk1B
        MEdJaUEyMllMc0J3ZWx5bG9qY1d1UEUK7DIdChXw6azXc58C4sJGDy+9tGaIxGUV
        JytolFKyjUwcuPMgvS6BXmYWUpfuSimgKp7oTf/qPwkRGly9po1hjQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-17T22:09:02Z"
  mac: ENC[AES256_GCM,data:S9dnKlGl57Df9TEMZqU/kbLc/NC+9+ayEp5XCwRtuRNI2XBEu/JYQXWeVoQ2ViN7PHoIoKFcs0RYlhy15SnzOnDLAf+uBF8QVYM8XcCXDYOrxAo/ecAS3ZBEnlQMzTEDf4DGfEexJsvUoTg+q6Bvp0236/SXOGQcp0qQaa4stF8=,iv:+Nhy2i9ua5Ryx0lvNe0EOPI2fOT8n6uEatErhMppnmU=,tag:LzTh/oOKm0EdHnKp23D5sQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
