apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:MkmOTne+IIlk3D7BDAfN,iv:2m6oOSKpfreBnGo/vzfkcKHovHXarpxmQy3PtMRLbks=,tag:cWRVOdszER6recyoDN7hXA==,type:str]
sops:
  age:
    - recipient: age130g6zdklea9zw6n4ddm7ffn4dewvyexjps0q9zfse2df72umqazslr0lc3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWTc3TFpLaXRMd1ZWSDc1
        NXlLcEs5N2ZkM216N3o3bWZZNnlVamQ3bWc4Ci9VdDNmZHFObzFXZy9lRmtSN1VR
        YllTWnlGeVpSWnNUUGVXWWlGNWhSRVUKLS0tIGEwdlJSalRtZEEyUWdWanQwM2Mz
        SmRnejQ2aXR1M1NzckVXY3pseE5IZ1EKinA64Gp0bY9NIjW1gE3/tPQ7mVjGVw79
        oADh+vOI2pBc4DPpsVB6ALn8r2GQL9f+/JdQ8BcEM3wJlSpmQsof0w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-17T22:09:02Z"
  mac: ENC[AES256_GCM,data:+IqESNJaSlpGlgZKOl96O9ecBVRZKlvi1prN0cGhOnUYVVceWZPpYdFmf6NAcNv3yxgb4wVu3iDZCTB32pA0PklUzuRXyD8ACHYpCDYIBKWnh8+dP5S/wklbucDaYigqkMZF81vwyl0ZugJAFTfCxXEeGSyx1dGz+aeDZfOzVfs=,iv:MgcXvRdgLQddTe2Em8STA7YUvxntgHj9wSb3rK8q4aY=,tag:diuiBCf2yweRMvTTO+My9w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
