apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Eq55T/y+bq8LUDarZOAmIQUYFXU21ccizjxUbGvx9kY=,iv:AbYMXdp0rpG6E4bvvFkwZggc/yHlalPwgxZS6kw6LQ8=,tag:rxvnLW/Z6/6zwPNolZKzGA==,type:str]
sops:
  age:
    - recipient: age130g6zdklea9zw6n4ddm7ffn4dewvyexjps0q9zfse2df72umqazslr0lc3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaUpzYm1xK0hNdUFwWjlS
        YTV6NTZpOFA1RDE2NE8vdWs1TzVpU3I0dkgwCm9ZQkpJK2pVUTJPclU2SVIzOXlP
        WnI2ZFdxcVJCQklJQ3dEV1NtUHpQZlkKLS0tIDZlaGJ4aks4bHF0N2FYa0pzb2pZ
        eVJMRFlLRjFNMFIzcGVLQ1VmNHphMmsK+1RBCVgdAGxb0JFGKaJP1CfEjhj68GAG
        9hlmXpgDu8/b3ln9wDb+YoSEQjvS6j1Tjo/vtt5LoZckgIPkTJppbw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-17T22:09:02Z"
  mac: ENC[AES256_GCM,data:Jxjdi5/luK8YuNzVa4mJa0IKQvf8LckiApQ0O/Ug7DIZqCT1zQMsdxdzIzKd1jx5WCwKt/9a8exAQuBb+gi/kfvh4PDq0TDcuGx0SrYhZPGvbw6PybxgwPfcAGaghacYqWlNX516RYjKkDMPrJsn3PR/o1XU5VFm49ya/OIkE/A=,iv:aRqk/1KYj72XnaGMmtGUA5WCNRYdW+nPAD9VqL+I4is=,tag:V4ddh5AMovHRbInIfMdBpQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
