apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:nuVBmcAnb3RrkNGcuUD/e0XfrVAPswOD2AqMJ0RNryVDS9DqroS6t2KZyDHEDjmejnlzu2EB3UBx7LDF6NBmHuSx16iLPMB8WiJ9NMO8elDG/2jYqSIi1XMxKfZ4J+HDXFUvU4xWc+jZEdVkWyBdBeSX/wFB0dtVGeKTeUy82av+cZioQjiuafmzd/PPB3rEBOh8fBZ7QEMnC4fiuRH8YFKpOWpbmH5YZuIQHYyW0EtuLuaX,iv:vC20c5r+OcFeDAkl463xrjE7AO8PcdT07RimFK9tHvk=,tag:T8XLJe7X6B7ZiYHynwlVow==,type:str]
sops:
  age:
    - recipient: age130g6zdklea9zw6n4ddm7ffn4dewvyexjps0q9zfse2df72umqazslr0lc3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyU3d5RDl0ZVd6K3VhUlI5
        YUJmdjhsSEZRNmdXMTBhVGNXVVBiVnJDalc4CmtReHlhbTVVYXRxVFV4RGhudVEy
        RGlqQWowK2x5bWVrbDlzNlExNG1wYU0KLS0tIDF3dVZLaEdtNHI1bWM3VWdtV2tQ
        VURDTHhudk5Oc1djVlk0Vk9RVzJUdTgKMttLWniTr6J4Oah0/ELkOvs7E+qgKEHr
        F7NY7zF0MXZA+IvdgebZmaQ2aSfMsUh5DWz/N5RiNuKVmU9pA2J64w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-17T22:09:02Z"
  mac: ENC[AES256_GCM,data:d5w9qLevpXeXTzOJCkLs4IFGMBKeo0TfQZYk3IUxbWg44I0Pv+mKhJEtIDKEoZ1T2d3J4sObEZRo9sV2TX5vIH2sjhA9e6vN/DbtZKamJC5q+7ylwpCL5Ds/R8Lkxc0izDuV5lSeUDkpPe01L2Wd4Y5BWlqvh/qew+CiW1iLPlQ=,iv:Yzp9qQTVfDyrHGQkkPGs4lfetLPzjmZHNOSbwBKHqws=,tag:jD2aSJETKZP+R57KpudC4g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
