---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-secrets-operator
spec:
  chartRef:
    kind: OCIRepository
    name: external-secrets-operator
  interval: 1h
  values:
    fullnameOverride: *app
    installCRDs: true
    serviceMonitor:
      enabled: true
