---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: librechat
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/default/librechat/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  targetNamespace: default
  dependsOn:
    - name: external-secrets-operator
      namespace: flux-system
