apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:ylOZKBk/6lxnDuoB9DrNjVgmrsDYPjU/NYGxP1WgmBrSITZ5Dn2zrw==,iv:N7YG95a/wlqOJfHAY1MNhogi50JJL6ASest3V+aZutQ=,tag:IotlPvSfJoxGvj5RnmTAoA==,type:str]
sops:
  age:
    - recipient: age130g6zdklea9zw6n4ddm7ffn4dewvyexjps0q9zfse2df72umqazslr0lc3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDYkNSSW55Q2VKNEFKTzVY
        ODdjd0NpVEZjMUdjNTF2R1djZjJnempjbFVvCm1Mb0gyeWhVN3pYSDF6cVVHWXJC
        MGVPd3NwL2dqY1BacGhvcHZFNmFCVncKLS0tIEgzaElVK28xR1lzbTdtRjVJR09R
        MGtMckFKUTNMN1FsSXFkTXdJekszV1UK7hNa7Z5jgB56cBKGyiB5J2R3fJmHrhhb
        rNHWgqbpvigKb/motteZP1Vin9llqad9KIfG/UEuZOW+vdfgslWdDA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-17T22:09:02Z"
  mac: ENC[AES256_GCM,data:ODM5929GI1JHrTqZsDR3A1ZSk6BTlahuAmODQGCgr581/SPzI5ye8sJayA7v+HbTscui6+1IYZgkQU/BacRJGWaMFdQbV0SSASbq16B5iioOGh/dnNUmaLNM8hA8abY19FQcFVl4DHYgydoJz06458RWBnbTk00T79EotzFJCkw=,iv:qghfsRcVpXF/4d4anXHON8f6qakufcvGsYF+uo61gYo=,tag:Z8Ic2hc581lMl4s4eN3yMA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
