---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capacitor
rules:
  # Flux resources
  - apiGroups: ["source.toolkit.fluxcd.io"]
    resources:
      - gitrepositories
      - ocirepositories
      - helmrepositories
      - helmcharts
      - buckets
    verbs: ["get", "list", "watch", "kind"]
  - apiGroups: ["infra.contrib.fluxcd.io"]
    resources:
      - terraforms
    verbs: ["get", "list", "watch", "kind"]    
  - apiGroups: ["kustomize.toolkit.fluxcd.io"]
    resources:
      - kustomizations
    verbs: ["get", "list", "watch", "kind"]
  - apiGroups: ["helm.toolkit.fluxcd.io"]
    resources:
      - helmreleases
    verbs: ["get", "list", "watch", "spec"]
  - apiGroups: ["notification.toolkit.fluxcd.io"]
    resources:
      - alerts
      - providers
      - receivers
    verbs: ["get", "list", "watch", "kind"]
  - apiGroups: ["image.toolkit.fluxcd.io"]
    resources:
      - imagerepositories
      - imagepolicies
      - imageupdateautomations
    verbs: ["get", "list", "watch", "kind"]
  # Core Kubernetes resources
  - apiGroups: [""]
    resources:
      - namespaces
      - events
      - pods
      - services
    verbs: ["get", "list", "watch", "kind"]
  - apiGroups: ["apps"]
    resources:
      - deployments
      - daemonsets
      - statefulsets
      - replicasets
    verbs: ["get", "list", "watch", "kind"]
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs: ["get", "list", "watch", "kind"]
