---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: librechat
  namespace: default
spec:
  interval: 12h
  url: oci://ghcr.io/danny-avila/librechat-chart/librechat
  ref:
    semver: "*"
