---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: librechat
  namespace: default
spec:
  hostnames: ["chat.k8s.alexieff.io"]
  parentRefs:
    - name: envoy-external
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: librechat-librechat
          port: 3080
